# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161111_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='sseaver321@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
