# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161114_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='map_url',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
