# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161114_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 14, 19, 41, 48, 822938, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
