# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161114_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 14, 20, 14, 4, 128170, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 11, 14, 20, 14, 12, 423257, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
