# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161115_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sport',
            field=models.ManyToManyField(to='app.Sport'),
        ),
    ]
