# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161116_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_sports',
            field=models.ManyToManyField(blank=True, to='app.Sport'),
        ),
    ]
