# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161116_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
