# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
