# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161123_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=7),
            preserve_default=False,
        ),
    ]
