# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_event_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=7),
        ),
    ]
